### ISSUE TITLE
Navigating from participants to camera view does not load the camera

### ISSUE THREAD

**Issue by justintricate** [Team-Celsius/Halfsies#37]

**Comment by michaeltimo** [comment]
Unable to replicate this bug on iOS

**Comment by justintricate** [comment]
@sking11 brought this bug up, & has an iPhone.. maybe an emulator issue? or specific model of iPhone?

**Comment by michaeltimo** [comment]
Could be, am running off of an iPhone 11

**Comment by justintricate** [comment]
appears fixed, can re-open if it arises again
